# Generated by Django 5.1.6 on 2025-07-08 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleLoginHistory',
        ),
    ]
